global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10000s
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - to: 'tim.oberlaender@stud.uni-goettingen.de'
        from: 'tim.oberlaender@stud.uni-goettingen.de'
        smarthost: email.stud.uni-goettingen.de:587
        auth_username: 'tim.oberlaender@student.uni-goettingen.de'
        auth_identity: 'tim.oberlaender@student.uni-goettingen.de'
        auth_password: 'xxxx'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']