{
 "title": "spring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{__name__}}" },
    { "expr": "system_cpu_usage", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Up-Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{ instance=\"localhost:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"localhost:8080\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Started at ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{ instance=\"localhost:8080\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "http", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_global_error_total{instance=\"localhost:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{instance=\"localhost:8080\",  exception=\"None\", uri!~\".*actuator.*\"} / http_server_requests_seconds_count{instance=\"localhost:8080\",  exception=\"None\", uri!~\".*actuator.*\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "request time maximum",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "count of requests by seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 20 },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{instance=\"localhost:8080\", application=\"\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "allocated JVM memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_gc_memory_allocated_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC pauses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 29 },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{instance=\"localhost:8080\"}[5m])",
     "legendFormat": "{{action}}"
    }
   ]
  }
 ]
}